### ISSUE TITLE
Mention Google Voice/Hangouts

### ISSUE THREAD

**Issue by rking** [PeopleAdmin/tweemux#17]
As much as I loathe Google's looming size, it is true that Google communication
tools might work for people where SIP/Skype/POTS might not.

**Comment by jjasghar** [comment]
I completely agree. Opscode uses it and its been crazy great.

+1 on converting/using google hangouts.
- JJ Asghar

On Mar 2, 2013, at 18:47, "☈king" <notifications@github.com<mailto:notifications@github.com>> wrote:

As much as I loathe Google's looming size, it is true that Google communication
tools might work for people where SIP/Skype/POTS might not.
