### ISSUE TITLE
If tmux isn't in the path when you SSH in, nothing will work.

### ISSUE THREAD

**Issue by acook** [PeopleAdmin/tweemux#19]
``` shell
$ tweemux at xxx.xxx.xxx.xxx
: Running; ssh xxx.xxx.xxx.xxx -t tmux -S /tmp/tweemux.sock attach  # Connect to xxx.xxx.xxx.xxx, demand a pty, then attach to session
Password:
bash: tmux: command not found
Connection to xxx.xxx.xxx.xxx closed.
```

Since I'm using Homebrew, `tmux` isn't in the default path.

What I had to do was change my `/etc/sshd_config` to `AllowUserEnvironment` to `yes`, and then add this to my pair user's `~/.ssh/environment` file:

``` shell
PATH=/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/X11/bin:/usr/local/share/npm/bin/
```

You don't actually need the NPM or CoreUtils paths, but I figured what the hell.

Anyway, is there another way of handling this?

**Comment by rking** [comment]
Yes, this is a flaw in the current OSX handling on my part.

I need to just make it so `brew install <someurl>` does the right things, I think.

**Comment by rking** [comment]
I can't get to this until after work, but here's the start, taken straight from wemux:

``` ruby
require 'formula'

class Tweemux < Formula
  homepage 'http://github.com/PeopleAdmin/tweemux#readme'
  url 'http://github.com/PeopleAdmin/tweemux'
  sha1 'cccdcf5042c6ab463ba34fa0b6b4b80ac3c828e8'

  depends_on 'tmux'
  depends_on 'tweemux' => :ruby

  def install
    tmux_in_default_path = '/usr/bin/tmux'
    system %W(sudo ln -s /usr/local/bin/tmux #{tmux_in_default_path}) \
      unless File.exists? tmux_in_default_path
  end

  def test
    system 'tweemux help'
  end
end
```

**Comment by acook** [comment]
Is `/usr/bin` in the path by default on OSX?

**Comment by rking** [comment]
On Wed, Mar 06, 2013 at 03:32:47PM -0800, Anthony Cook wrote:

> Is /usr/bin in the path by default on OSX?

Sure is!

Look for something that works with 'brew install' either tonight, or look
for it tomorrow morning, or look for me to be hiding behind something
because I failed to get it done either of those two times.

-☈

**Comment by rking** [comment]
@acook - the PATH part of this should be fixed in master.

Now, I still need to do the user/sshd part of it.  That might actually be a good thing to pair on, if you want.

My contact info, in no particular order:
rking on irc.freenode.net (buncha channels, mainly #sharpsaw )
muxmuch@sharpsaw.org
sip:ahrkeeng@ekiga.net
skype:RyanJosephKing
806-368-2965

Let me know if it needs more work before we can close the first part of this Issue out, and then we'll start hammering out the conversation for the remainder.
