### ISSUE TITLE
Guest unable to specify user name.

### ISSUE THREAD

**Issue by acook** [PeopleAdmin/tweemux#20]
This requires you to know the guest's local username as well as setting up individual accounts per guest.

**Comment by acook** [comment]
This is what I get for not looking at the source. Doh!

**Comment by rking** [comment]
BTW, the way I use it is I ask them their preferred username (and ask them the output of `whoami` if they happen to be less-technical and aren't sure of the answer to that), then I add a user with their `whoami` name, then run:

```
tweemux hubkey theirunixusername theirgithubusername
```

This will make it so they don't have to type a password to get in, but is also secure (more secure than passwords, actually).

@acook - If you want to pair up, let's find a higher bandwidth medium (chat, voice, etc.) and talk a bit. We'll definitely make sure your tweemux use cases are covered thoroughly.

**Comment by acook** [comment]
I totally used `hubkey` the other day :grinning: it worked great.

Since I work with a distributed team - people in the office in SF, sometimes me at home, a guy in the suburbs, and half a dozen people in south america, and about to pick up a guy in LA and maybe another in Portland - it's messier to have a bunch of users. 

Sure. I've been wanting to try Telephone.app, but Google Talk or Skype would work too. Thanks for building the tool, makes things really easy, especially since the harder parts are only on the host, really reduces the barrier to entry.
