### ISSUE TITLE
rbenv doesn't pick up on new bin/'s

### ISSUE THREAD

**Issue by rking** [PeopleAdmin/tweemux#33]
So `gem install tweemux && tweemux on ___` doesn't work for rbenv users.

The workaround is to have them do something like this:

```
gem install tweemux
exec $SHELL
tweemux on ___
```

And a possible workaround would be (untested):

```
gem install tweemux && bash -c 'tweemux on ___'
```

Which is kinda gross.

Perhaps the best thing would be one of those post-install messages (like from
HTTParty) where it detects the use of rbenv and tells them they'll have to
`exec $SHELL`.  Iunno.

**Comment by ntl** [comment]
When I tried `gem install tweemux && rbenv rehash && tweemux on ____` I seem to recall correct behavior.

`rbenv rehash` is absolutely key, however; it doesn't auto detect when new binaries have been installed by gems.

**Comment by rking** [comment]
They're talking about fixing this upstream. I'll let it take its natural course, there.
